[project]
name = "real-time-intrusion-detection-system-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "python-nmap>=0.7.1",
    "scapy>=2.6.1",
    "scikit-learn>=1.7.2",
]
